// A macro that takes the root files generated by my_code.C and uses them to graph the data for each momentum interval, along with all of the fits

#include "TFile.h"
#include "TF1.h"
#include "TH1F.h"
#include "TH2F.h"

void pt_combiner() {
    //Grab the files
    TFile* GaussianFile = new TFile("data/PionGaussianSparsesOutput.root", "READ");
    TFile* ExpGaussianFile = new TFile("data/PionExponential_GaussianSparsesOutput.root", "READ");
    TFile* CrystalBallFile = new TFile("data/PionCrystal_BallSparsesOutput.root", "READ");
    
    //Grab the data from the files
    TH1D* GaussianData = 0;
    TH1D* ExpGaussianData = 0;
    TH1D* CrystalBallData = 0;
    
    GaussianFile->GetObject("mass_pion", GaussianData);
    ExpGaussianFile->GetObject("mass_pion", ExpGaussianData);
    CrystalBallFile->GetObject("mass_pion", CrystalBallData);
    
    // From each data object, get the fit function
    TF1* GaussianFit = (TF1*) GaussianData->GetListOfFunctions()->FindObject("fit");
    TF1* ExpGaussianFit = (TF1*) ExpGaussianData->GetListOfFunctions()->FindObject("fit");
    TF1* CrystalBallFit = (TF1*) CrystalBallData->GetListOfFunctions()->FindObject("fit");
    
    // Create a TCanvas for graphing; as a test, graph out the fits
    TCanvas* canvas = new TCanvas();
    
    GaussianFit->Draw();
    ExpGaussianFit->SetLineColor(kBlue);
    ExpGaussianFit->Draw("same");
    CrystalBallFit->SetLineColor(kGreen);
    CrystalBallFit->Draw("same");
    canvas->SaveAs("testgraph.png");
    
    canvas->Close();
}
