// set_atlas_style and my_code should be run before this macro
// A macro that takes the root files generated by my_code.C and uses them to graph the data for each momentum interval, along with all of the fits
// Author: Ivan Chernyshev

#include "TFile.h"
#include "TF1.h"
#include "TH1F.h"
#include "TH2F.h"

const int colBlack = 1;
const int colRed = 2;
const int colGreen = 3;
const int colBlue = 4;
const int colYellow = 5;
const int colMagenta = 6;
const int colCyan = 7;
const int colClear = 10;

void pt_combiner() {
    
    const int num_of_samples = 8;
    char filenames[num_of_samples][50] = {"data/Pion0cutsSparsesOutput.root", "data/Pion1cutsSparsesOutput.root", "data/Pion2cutsSparsesOutput.root", "data/Pion3cutsSparsesOutput.root", "data/Pion4cutsSparsesOutput.root", "data/Pion5cutsSparsesOutput.root", "data/Pion6cutsSparsesOutput.root", "data/Pion7cutsSparsesOutput.root"};
    //Grab the files
    TFile* cutFiles[num_of_samples];
    for (int i = 0; i < num_of_samples; i++){
        cutFiles[i] = new TFile(filenames[i], "READ");
    }
    
    /**
    // Make an output root file
    TFile* OutputFile = new TFile("data_comparisons/Output.root", "RECREATE");
     */

    //Grab the data from the files
    TH1D* cutData[num_of_samples];
    TH1D* cutMassData[num_of_samples];
    TH1D* cutResiduals[num_of_samples];
    TF1* cutFits[num_of_samples];
    for (int i = 0; i < num_of_samples; i++) {
        cutData[i] = 0;
        cutMassData[i] = 0;
        cutResiduals[i] = 0;
        cutFiles[i]->GetObject("mass_pion", cutData[i]);
        cutFiles[i]->GetObject("unfitted_mass_pion", cutMassData[i]);
        cutFiles[i]->GetObject("residual", cutResiduals[i]);
        cutFits[i] = (TF1*) cutData[i]->GetListOfFunctions()->FindObject("fit");
    }
    
    // Create a TCanvas and TPads for graphing; graph out the fits, data, and residuals for the entire sample
    int colors[num_of_samples] = {kRed, kBlue, kGreen, kYellow, kCyan, kMagenta, kGray, kBlack};
    TCanvas* canvas = new TCanvas();
    TPad *pad[2] = {new TPad("pad0","",0,0.38,1,1), new TPad("pad1","",0,0,1,0.46)};
    
    // Graph main data
    canvas->cd();
    pad[0]->Draw();
    pad[0]->cd();
    cutMassData[0]->GetYaxis()->SetTitle("Number of Entries");
    cutMassData[0]->GetYaxis()->SetTitleSize(.07);
    cutMassData[0]->GetYaxis()->SetTitleOffset(0.6);
    cutMassData[0]->SetMarkerColor(colors[0]);
    cutMassData[0]->Draw();
    cutFits[0]->SetLineColor(colors[0]);
    cutFits[0]->Draw("same");
    for (int i = 1; i < num_of_samples; i++) {
        cutMassData[i]->SetMarkerColor(colors[i]);
        cutMassData[i]->Draw("same");
        cutFits[i]->SetLineColor(colors[i]);
        cutFits[i]->Draw("same");
    }
    myBoxText(0.20, 0.90, 0.05, colClear, colors[0], "No cuts done");
    myBoxText(0.20, 0.85, 0.05, colClear, colors[1], "Cuts: dR");
    myBoxText(0.20, 0.80, 0.05, colClear, colors[2], "Cuts: dR and asymmetry");
    myBoxText(0.20, 0.75, 0.05, colClear, colors[3], "Additional cut: angle");
    myBoxText(0.20, 0.70, 0.05, colClear, colors[4], "Additional cut: Ncells");
    myBoxText(0.20, 0.65, 0.05, colClear, colors[5], "Additional cut: DisToBorder");
    myBoxText(0.20, 0.60, 0.05, colClear, colors[6], "Additional cut: DisToBadChannel");
    myBoxText(0.20, 0.55, 0.05, colClear, colors[7], "Additional cut: lambda02");
    // Graph residuals
    canvas->cd();
    pad[1]->Draw();
    pad[1]->cd();
    cutResiduals[0]->GetYaxis()->SetTitle("Residuals");
    cutResiduals[0]->GetYaxis()->SetTitleSize(.07);
    cutResiduals[0]->GetYaxis()->SetTitleOffset(0.3);
    cutResiduals[0]->GetXaxis()->SetTitleSize(.06);
    cutResiduals[0]->GetXaxis()->SetTitleOffset(0.8);
    cutResiduals[0]->SetMarkerColor(kRed);
    cutResiduals[0]->Draw("P");
    for (int i = 1; i < num_of_samples; i++) {
        cutResiduals[i]->SetMarkerColor(colors[i]);
        cutResiduals[i]->Draw("P same");
    }
    canvas->SaveAs("data_comparisons/testgraph.png");
    
    // Write residuals to the output root file
    TMultiGraph* residualpackage = new TMultiGraph();
    residualpackage->Add(new TGraph(cutResiduals[0]));
    residualpackage->Add(new TGraph(cutResiduals[1]));
    residualpackage->Add(new TGraph(cutResiduals[2]));
    residualpackage->Add(new TGraph(cutResiduals[3]));
    residualpackage->Add(new TGraph(cutResiduals[4]));
    residualpackage->Add(new TGraph(cutResiduals[5]));
    residualpackage->SetTitle("Residuals over Momentum; Mass (GeV); Entry residual");
    residualpackage->Write("residuals");
    
    // Graph the momentum chart
    canvas->Clear();
    TH1D* Momentum = 0;
    cutFiles[0]->GetObject("Momentum-entries_chart", Momentum);
    Momentum->Draw();
    canvas->SaveAs("data_comparisons/Momentum_Graph.png");
    
    // Repeat for each of the following momentum intervals: 8-10 GeV, 10-11 GeV, 11-12 GeV, 12-13 GeV, 13-15 GeV
    canvas->Clear();
    const int num_of_intervals = 6;
    double intervals[num_of_intervals][2] = {{8.0, 10.0}, {10.0, 11.0}, {11.0, 12.0}, {12.0, 13.0}, {13.0, 15.0}, {15.0, 20.0}};
    for(int i = 0; i < num_of_intervals; i++) {
        // Set up the pads and the min and max momenta
        double min = intervals[i][0];
        double max = intervals[i][1];
        pad[0] = new TPad("pad0","",0,0.38,1,1);
        pad[1] = new TPad("pad1","",0,0,1,0.46);
        
        // load data
        TH1D* cutData[num_of_samples];
        TH1D* cutMassData[num_of_samples];
        TH1D* cutResiduals[num_of_samples];
        TF1* cutFits[i];
        for (int i = 0; i < num_of_samples; i++) {
            cutFiles[i]->GetObject(Form("mass-pion-%2.2fGeV-%2.2fGeV", min, max), cutData[i]);
            cutFiles[i]->GetObject(Form("unfitted_mass_pion-%2.2fGeV-%2.2fGeV", min, max), cutMassData[i]);
            cutFiles[i]->GetObject(Form("residual-%2.2fGeV-%2.2fGeV", min, max), cutResiduals[i]);
            cutFits[i] = (TF1*) cutData[i]->GetListOfFunctions()->FindObject("fit");
        }
        // Graph mass data
        canvas->cd();
        pad[0]->Draw();
        pad[0]->cd();
        cutMassData[0]->GetYaxis()->SetTitle("Number of Entries");
        cutMassData[0]->GetYaxis()->SetTitleSize(.07);
        cutMassData[0]->GetYaxis()->SetTitleOffset(0.6);
        cutMassData[0]->SetMarkerColor(colors[0]);
        //cutMassData[0]->GetYaxis()->SetRangeUser(-1.0, 1400.0);
        cutMassData[0]->Draw();
        cutFits[0]->SetLineColor(colors[0]);
        cutFits[0]->Draw("same");
        for (int i = 1; i < num_of_samples; i++) {
            cutMassData[i]->SetMarkerColor(colors[i]);
            cutMassData[i]->Draw("same");
            cutFits[i]->SetLineColor(colors[i]);
            cutFits[i]->Draw("same");
        }
        myBoxText(0.20, 0.90, 0.05, colClear, colors[0], "No cuts done");
        myBoxText(0.20, 0.85, 0.05, colClear, colors[1], "Cuts: dR");
        myBoxText(0.20, 0.80, 0.05, colClear, colors[2], "Cuts: dR and asymmetry");
        myBoxText(0.20, 0.75, 0.05, colClear, colors[3], "Additional cut: angle");
        myBoxText(0.20, 0.70, 0.05, colClear, colors[4], "Additional cut: Ncells");
        myBoxText(0.20, 0.65, 0.05, colClear, colors[5], "Additional cut: DisToBorder");
        myBoxText(0.20, 0.60, 0.05, colClear, colors[6], "Additional cut: DisToBadChannel");
        myBoxText(0.20, 0.55, 0.05, colClear, colors[7], "Additional cut: lambda02");
        // Graph residuals
        canvas->cd();
        pad[1]->Draw();
        pad[1]->cd();
        cutResiduals[0]->GetYaxis()->SetTitle("Residuals");
        cutResiduals[0]->GetYaxis()->SetTitleSize(.07);
        cutResiduals[0]->GetYaxis()->SetTitleOffset(0.3);
        cutResiduals[0]->GetXaxis()->SetTitleSize(.06);
        cutResiduals[0]->GetXaxis()->SetTitleOffset(0.8);
        cutResiduals[0]->SetMarkerColor(kRed);
        cutResiduals[0]->Draw("P");
        for (int i = 1; i < num_of_samples; i++) {
            cutResiduals[i]->SetMarkerColor(colors[i]);
            cutResiduals[i]->Draw("P same");
        }
        //Save file
        canvas->SaveAs(Form("data_comparisons/testgraph_%2.2fGeV-%2.2fGeV.png", min, max));
    }
    
    // Graph the mass vs momentum for each model
    canvas->Clear();
    // Fetch data
    TGraph* mass_mom_cuts[num_of_samples];
    for (int i = 0; i < num_of_samples; i++) {
        mass_mom_cuts[i] = 0;
        cutFiles[i]->GetObject("mean-masses", mass_mom_cuts[i]);
    }
    // Create the constant reference
    TF1* real_mass = new TF1("real_mass_momentum", "[0]", 8, 20);
    real_mass->SetParameter(0, 0.13498);
    real_mass->SetLineWidth(2);
    real_mass->SetLineColor(kBlack);
    real_mass->GetYaxis()->SetRangeUser(.125, .170);
    // Graph everything
    real_mass->Draw();
    for (int i = 0; i < num_of_samples; i++) {
        mass_mom_cuts[i]->SetLineColor(colors[i]);
        mass_mom_cuts[i]->SetMarkerColor(colors[i]);
        mass_mom_cuts[i]->Draw("same");
    }
    myBoxText(0.50, 0.36, 0.05, colClear, colors[0], "No cuts done");
    myBoxText(0.50, 0.33, 0.05, colClear, colors[1], "Cuts: dR");
    myBoxText(0.50, 0.30, 0.05, colClear, colors[2], "Cuts: dR and asymmetry");
    myBoxText(0.50, 0.27, 0.05, colClear, colors[3], "Additional cut: angle");
    myBoxText(0.50, 0.24, 0.05, colClear, colors[4], "Additional cut: Ncells");
    myBoxText(0.50, 0.21, 0.05, colClear, colors[5], "Additional cut: DisToBorder");
    myBoxText(0.50, 0.18, 0.05, colClear, colors[6], "Additional cut: DisToBadChannel");
    myBoxText(0.50, 0.15, 0.05, colClear, colors[7], "Additional cut: lambda02");
    //Save
    canvas->SaveAs("data_comparisons/MassvsMomentum.png");
    
    // Graph mass width vs momentum for each interval
    canvas->Clear();
    // Fetch data
    TGraph* width_mom_cuts[num_of_samples];
    for (int i = 0; i < num_of_samples; i++) {
        width_mom_cuts[i] = 0;
        cutFiles[i]->GetObject("standard-dev-masses", width_mom_cuts[i]);
    }
    // Graph everything
    width_mom_cuts[0]->SetLineColor(colors[0]);
    width_mom_cuts[0]->SetMarkerColor(colors[0]);
    width_mom_cuts[0]->GetYaxis()->SetRangeUser(4., 25.);
    width_mom_cuts[0]->Draw();
    for (int i = 1; i < num_of_samples; i++) {
        width_mom_cuts[i]->SetLineColor(colors[i]);
        width_mom_cuts[i]->Draw("same");
    }
    myBoxText(0.20, 0.85, 0.05, colClear, colors[0], "No cuts done");
    myBoxText(0.20, 0.80, 0.05, colClear, colors[1], "Cuts: dR");
    myBoxText(0.20, 0.75, 0.05, colClear, colors[2], "Cuts: dR and asymmetry");
    myBoxText(0.20, 0.70, 0.05, colClear, colors[3], "Additional cut: angle");
    myBoxText(0.20, 0.65, 0.05, colClear, colors[4], "Additional cut: Ncells");
    myBoxText(0.20, 0.60, 0.05, colClear, colors[5], "Additional cut: DisToBorder");
    myBoxText(0.20, 0.55, 0.05, colClear, colors[6], "Additional cut: DisToBadChannel");
    myBoxText(0.20, 0.50, 0.05, colClear, colors[7], "Additional cut: lambda02");
    //Save
    canvas->SaveAs("data_comparisons/MassWidthvsMomentum.png");

    // Graph peak integral for each interval
    canvas->Clear();
    // Fetch data
    TGraph* integral_mom_cuts[num_of_samples];
    for (int i = 0; i < num_of_samples; i++) {
        integral_mom_cuts[i] = 0;
        cutFiles[i]->GetObject("pion-integrals", integral_mom_cuts[i]);
    }
    // Graph everything
    integral_mom_cuts[0]->SetLineColor(colors[0]);
    integral_mom_cuts[0]->SetMarkerColor(colors[0]);
    integral_mom_cuts[0]->GetYaxis()->SetRangeUser(0.0, 8000.);
    integral_mom_cuts[0]->Draw();
    for (int i = 1; i < num_of_samples; i++){
        integral_mom_cuts[i]->SetLineColor(colors[i]);
        integral_mom_cuts[i]->Draw("same");
    }
    myBoxText(0.50, 0.88, 0.05, colClear, colors[0], "No cuts done");
    myBoxText(0.50, 0.83, 0.05, colClear, colors[1], "Cuts: dR");
    myBoxText(0.50, 0.78, 0.05, colClear, colors[2], "Cuts: dR and asymmetry");
    myBoxText(0.50, 0.73, 0.05, colClear, colors[3], "Additional cut: angle");
    myBoxText(0.50, 0.68, 0.05, colClear, colors[4], "Additional cut: Ncells");
    myBoxText(0.50, 0.63, 0.05, colClear, colors[5], "Additional cut: DisToBorder");
    myBoxText(0.50, 0.58, 0.05, colClear, colors[6], "Additional cut: DisToBadChannel");
    myBoxText(0.50, 0.53, 0.05, colClear, colors[7], "Additional cut: lambda02");
    //Save
    canvas->SaveAs("data_comparisons/PeakIntegralvsMomentum.png");
    
    canvas->Close();
}
