// A macro that takes the root files generated by my_code.C and uses them to graph the data for each momentum interval, along with all of the fits

#include "TFile.h"
#include "TF1.h"
#include "TH1F.h"
#include "TH2F.h"
#include "atlasstyle-00-03-05/AtlasStyle.h"
#include "atlasstyle-00-03-05/AtlasStyle.C"
#include "atlasstyle-00-03-05/AtlasUtils.h"
#include "atlasstyle-00-03-05/AtlasUtils.C"
#include "atlasstyle-00-03-05/AtlasLabels.h"
#include "atlasstyle-00-03-05/AtlasLabels.C"

const int colBlack = 1;
const int colRed = 2;
const int colGreen = 3;
const int colBlue = 4;
const int colClear = 10;

void pt_combiner_old_comparison() {
    // Set ATLAS style
    gROOT->LoadMacro("AtlasStyle.C");
    SetAtlasStyle();
    
    //Grab the files
    TFile* GaussianFile = new TFile("data/PionGaussianSparsesOutput.root", "READ");
    TFile* ExpGaussianFile = new TFile("data/PionExponential_GaussianSparsesOutput.root", "READ");
    TFile* CrystalBallFile = new TFile("data/PionCrystal_BallSparsesOutput.root", "READ");
    
    // Make an output root file
    TFile* OutputFile = new TFile("data_comparisons/Output.root", "RECREATE");

    
    //Grab the data from the files
    // Main data
    TH1D* GaussianData = 0;
    TH1D* ExpGaussianData = 0;
    TH1D* CrystalBallData = 0;
    TH1D* MassData = 0;
    
    GaussianFile->GetObject("mass_pion", GaussianData);
    ExpGaussianFile->GetObject("mass_pion", ExpGaussianData);
    CrystalBallFile->GetObject("mass_pion", CrystalBallData);
    GaussianFile->GetObject("unfitted_mass_pion", MassData);
    
    //residuals
    TH1D* GaussianResiduals = 0;
    TH1D* ExpGaussianResiduals = 0;
    TH1D* CrystalBallResiduals = 0;
    
    GaussianFile->GetObject("residual", GaussianResiduals);
    ExpGaussianFile->GetObject("residual", ExpGaussianResiduals);
    CrystalBallFile->GetObject("residual", CrystalBallResiduals);
    
    // From each data object, get the fit function
    TF1* GaussianFit = (TF1*) GaussianData->GetListOfFunctions()->FindObject("fit");
    TF1* ExpGaussianFit = (TF1*) ExpGaussianData->GetListOfFunctions()->FindObject("fit");
    TF1* CrystalBallFit = (TF1*) CrystalBallData->GetListOfFunctions()->FindObject("fit");
    
    // Create a TCanvas and TPads for graphing; graph out the fits, data, and residuals for the entire sample
    TCanvas* canvas = new TCanvas();
    TPad *pad[2] = {new TPad("pad0","",0,0.38,1,1), new TPad("pad1","",0,0,1,0.46)};
    
    canvas->cd();
    pad[0]->Draw();
    pad[0]->cd();
    MassData->GetYaxis()->SetTitle("Number of Entries");
    MassData->GetYaxis()->SetTitleSize(.07);
    MassData->GetYaxis()->SetTitleOffset(0.6);
    MassData->Draw();
    GaussianFit->SetLineColor(kRed);
    GaussianFit->Draw("same");
    ExpGaussianFit->SetLineColor(kBlue);
    ExpGaussianFit->Draw("same");
    CrystalBallFit->SetLineColor(kGreen);
    CrystalBallFit->Draw("same");
    MassData->GetListOfFunctions()->Add(GaussianFit);
    MassData->GetListOfFunctions()->Add(ExpGaussianFit);
    MassData->GetListOfFunctions()->Add(CrystalBallFit);
    myMarkerText(0.60, 0.85, colBlack, 20, "Pi0 Data",1.0);
    myBoxText(0.60, 0.80, 0.05, colClear, colRed, "Gaussian Model");
    myBoxText(0.60, 0.75, 0.05, colClear, colBlue, "Exponentially Modified Gaussian Model");
    myBoxText(0.60, 0.70, 0.05, colClear, colGreen, "Crystal Ball Model");
    MassData->Write("mass-entry_fits");
    
    canvas->cd();
    pad[1]->Draw();
    pad[1]->cd();
    GaussianResiduals->GetYaxis()->SetTitle("Residuals");
    GaussianResiduals->GetYaxis()->SetTitleSize(.07);
    GaussianResiduals->GetYaxis()->SetTitleOffset(0.3);
    GaussianResiduals->GetXaxis()->SetTitleSize(.06);
    GaussianResiduals->GetXaxis()->SetTitleOffset(0.8);
    GaussianResiduals->SetMarkerColor(kRed);
    GaussianResiduals->Draw("P");
    ExpGaussianResiduals->SetMarkerColor(kBlue);
    ExpGaussianResiduals->Draw("P same");
    CrystalBallResiduals->SetMarkerColor(kGreen);
    CrystalBallResiduals->Draw("P same");
    canvas->SaveAs("data_comparisons/testgraph.png");
    
    // Write residuals to the output root file
    TMultiGraph* residualpackage = new TMultiGraph();
    residualpackage->Add(new TGraph(GaussianResiduals));
    residualpackage->Add(new TGraph(ExpGaussianResiduals));
    residualpackage->Add(new TGraph (CrystalBallResiduals));
    residualpackage->SetTitle("Residuals over Momentum; Mass (GeV); Entry residual");
    residualpackage->Write("residuals");
    
    // Graph the momentum chart
    canvas->Clear();
    TH1D* Momentum = 0;
    GaussianFile->GetObject("Momentum-entries_chart", Momentum);
    Momentum->Draw();
    canvas->SaveAs("data_comparisons/Momentum_Graph.png");
    
    // Repeat for each of the following momentum intervals: 8-10 GeV, 10-11 GeV, 11-12 GeV, 12-13 GeV, 13-15 GeV
    canvas->Clear();
    const int num_of_intervals = 5;
    double intervals[num_of_intervals][2] = {{8.0, 10.0}, {10.0, 11.0}, {11.0, 12.0}, {12.0, 13.0}, {13.0, 15.0}};
    for(int i = 0; i < num_of_intervals; i++) {
        // Set up the pads and the min and max momenta
        double min = intervals[i][0];
        double max = intervals[i][1];
        pad[0] = new TPad("pad0","",0,0.38,1,1);
        pad[1] = new TPad("pad1","",0,0,1,0.46);
        
        // load data
        GaussianFile->GetObject(Form("mass-pion-%2.2fGeV-%2.2fGeV", min, max), GaussianData);
        ExpGaussianFile->GetObject(Form("mass-pion-%2.2fGeV-%2.2fGeV", min, max), ExpGaussianData);
        CrystalBallFile->GetObject(Form("mass-pion-%2.2fGeV-%2.2fGeV", min, max), CrystalBallData);
        GaussianFile->GetObject(Form("unfitted_mass_pion-%2.2fGeV-%2.2fGeV", min, max), MassData);
        GaussianFile->GetObject(Form("residual-%2.2fGeV-%2.2fGeV", min, max), GaussianResiduals);
        ExpGaussianFile->GetObject(Form("residual-%2.2fGeV-%2.2fGeV", min, max), ExpGaussianResiduals);
        CrystalBallFile->GetObject(Form("residual-%2.2fGeV-%2.2fGeV", min, max), CrystalBallResiduals);
        GaussianFit = (TF1*) GaussianData->GetListOfFunctions()->FindObject("fit");
        ExpGaussianFit = (TF1*) ExpGaussianData->GetListOfFunctions()->FindObject("fit");
        CrystalBallFit = (TF1*) CrystalBallData->GetListOfFunctions()->FindObject("fit");
        
        // Graph
        canvas->cd();
        pad[0]->Draw();
        pad[0]->cd();
        MassData->GetYaxis()->SetTitle("Number of Entries");
        MassData->GetYaxis()->SetTitleSize(.07);
        MassData->GetYaxis()->SetTitleOffset(0.6);
        MassData->GetYaxis()->SetTitle("Number of Entries");
        MassData->Draw();
        GaussianFit->SetLineColor(kRed);
        GaussianFit->Draw("same");
        ExpGaussianFit->SetLineColor(kBlue);
        ExpGaussianFit->Draw("same");
        CrystalBallFit->SetLineColor(kGreen);
        CrystalBallFit->Draw("same");
        myMarkerText(0.60, 0.85, colBlack, 20, "Pi0 Data",1.0);
        myBoxText(0.60, 0.80, 0.05, colClear, colRed, "Gaussian Model");
        myBoxText(0.60, 0.75, 0.05, colClear, colBlue, "Exponentially Modified Gaussian Model");
        myBoxText(0.60, 0.70, 0.05, colClear, colGreen, "Crystal Ball Model");
        
        canvas->cd();
        pad[1]->Draw();
        pad[1]->cd();
        GaussianResiduals->GetYaxis()->SetTitle("Residuals");
        GaussianResiduals->GetYaxis()->SetTitleSize(.07);
        GaussianResiduals->GetYaxis()->SetTitleOffset(0.3);
        GaussianResiduals->GetXaxis()->SetTitleSize(.06);
        GaussianResiduals->GetXaxis()->SetTitleOffset(0.8);
        GaussianResiduals->GetYaxis()->SetTitle("Residuals");
        GaussianResiduals->SetMarkerColor(kRed);
        GaussianResiduals->Draw("P");
        ExpGaussianResiduals->SetMarkerColor(kBlue);
        ExpGaussianResiduals->Draw("P same");
        CrystalBallResiduals->SetMarkerColor(kGreen);
        CrystalBallResiduals->Draw("P same");
        
        //Save file
        canvas->SaveAs(Form("data_comparisons/testgraph_%2.2fGeV-%2.2fGeV.png", min, max));
    }
    
    // Graph the mass vs momentum for each model
    canvas->Clear();
    // Fetch data
    TGraph* mass_mom_gauss = 0;
    TGraph* mass_mom_expgauss = 0;
    TGraph* mass_mom_crystalball = 0;
    GaussianFile->GetObject("mean-masses", mass_mom_gauss);
    ExpGaussianFile->GetObject("mean-masses", mass_mom_expgauss);
    CrystalBallFile->GetObject("mean-masses", mass_mom_crystalball);
    
    // Create the constant reference
    TF1* real_mass = new TF1("real_mass_momentum", "[0]", 0, 20);
    real_mass->SetParameter(0, 0.13498);
    real_mass->SetLineWidth(2);
    real_mass->SetLineColor(kBlack);

    // Graph everything
    mass_mom_gauss->SetLineColor(kRed);
    mass_mom_expgauss->SetLineColor(kBlue);
    mass_mom_expgauss->SetMarkerColor(kBlue);
    mass_mom_crystalball->SetLineColor(kGreen);
    mass_mom_expgauss->Draw();
    mass_mom_gauss->Draw("same");
    mass_mom_crystalball->Draw("same");
    real_mass->Draw("same");
    myText(0.30, 0.95, colBlack, "Mass vs. Momentum");
    myBoxText(0.25, 0.85, 0.05, colClear, colBlack, "Actual pion mass");
    myBoxText(0.25, 0.80, 0.05, colClear, colRed, "Gaussian Model");
    myBoxText(0.25, 0.75, 0.05, colClear, colBlue, "Exponentially Modified Gaussian Model");
    myBoxText(0.25, 0.70, 0.05, colClear, colGreen, "Crystal Ball Model");

    
    //Save
    canvas->SaveAs("data_comparisons/MassvsMomentum.png");
    
    // Graph mass width vs momentum for each interval
    canvas->Clear();
    // Fetch data
    TGraph* width_mom_gauss = 0;
    TGraph* width_mom_expgauss = 0;
    TGraph* width_mom_crystalball = 0;
    GaussianFile->GetObject("standard-dev-masses", width_mom_gauss);
    ExpGaussianFile->GetObject("standard-dev-masses", width_mom_expgauss);
    CrystalBallFile->GetObject("standard-dev-masses", width_mom_crystalball);
    
    // Graph everything
    width_mom_gauss->SetLineColor(kRed);
    width_mom_expgauss->SetLineColor(kBlue);
    width_mom_crystalball->SetLineColor(kGreen);
    width_mom_crystalball->Draw();
    width_mom_expgauss->Draw("same");
    width_mom_gauss->Draw("same");
    width_mom_crystalball->Draw("same");
    myBoxText(0.25, 0.85, 0.05, colClear, colRed, "Gaussian Model");
    myBoxText(0.25, 0.80, 0.05, colClear, colBlue, "Exponentially Modified Gaussian Model");
    myBoxText(0.25, 0.75, 0.05, colClear, colGreen, "Crystal Ball Model");
    
    //Save
    canvas->SaveAs("data_comparisons/MassWidthvsMomentum.png");

    // Graph peak integral for each interval
    canvas->Clear();
    // Fetch data
    TGraph* integral_mom_gauss = 0;
    TGraph* integral_mom_expgauss = 0;
    TGraph* integral_mom_crystalball = 0;
    GaussianFile->GetObject("pion-integrals", integral_mom_gauss);
    ExpGaussianFile->GetObject("pion-integrals", integral_mom_expgauss);
    CrystalBallFile->GetObject("pion-integrals", integral_mom_crystalball);
    
    // Graph everything
    integral_mom_gauss->SetLineColor(kRed);
    integral_mom_expgauss->SetLineColor(kBlue);
    integral_mom_crystalball->SetLineColor(kGreen);
    integral_mom_expgauss->Draw();
    integral_mom_gauss->Draw("same");
    integral_mom_crystalball->Draw("same");
    myBoxText(0.25, 0.88, 0.05, colClear, colRed, "Gaussian Model");
    myBoxText(0.25, 0.83, 0.05, colClear, colBlue, "Exponentially Modified Gaussian");
    myBoxText(0.25, 0.78, 0.05, colClear, colGreen, "Crystal Ball Model");

    
    //Save
    canvas->SaveAs("data_comparisons/PeakIntegralvsMomentum.png");
    
    canvas->Close();
}
