// This macro is an auto-run script which repeatedly runs the background subtraction operation and ConpareHistograms

void autorun() {
    // 17q pp
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_XobsPb\", \"bkg_XobsPb\", \"hadj_XobsPb\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT__Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_XobsPb\", \"bkg_XobsPb\", \"hadj_XobsPb\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_XobsPb\", \"bkg_XobsPb\", \"hadj_XobsPb\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_dPhi\", \"bkg_dPhi\", \"hadj_dPhi\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_dPhi\", \"bkg_dPhi\", \"hadj_dPhi\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_dPhi\", \"bkg_dPhi\", \"hadj_dPhi\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_Xj\", \"bkg_Xj\", \"hadj_Xj\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_Xj\", \"bkg_Xj\", \"hadj_Xj\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_Xj\", \"bkg_Xj\", \"hadj_Xj\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_pTD\", \"bkg_pTD\", \"hadj_pTD\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_pTD\", \"bkg_pTD\", \"hadj_pTD\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_pTD\", \"bkg_pTD\", \"hadj_pTD\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_Multiplicity\", \"bkg_Multiplicity\", \"hadj_Multiplicity\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_Multiplicity\", \"bkg_Multiplicity\", \"hadj_Multiplicity\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__17q_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_Multiplicity\", \"bkg_Multiplicity\", \"hadj_Multiplicity\", 0.57, 0.03)");
    
    // 13def pPb
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_XobsPb\", \"bkg_XobsPb\", \"hadj_XobsPb\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_XobsPb\", \"bkg_XobsPb\", \"hadj_XobsPb\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT__DNN.root\", \"sig_XobsPb\", \"bkg_XobsPb\", \"hadj_XobsPb\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_dPhi\", \"bkg_dPhi\", \"hadj_dPhi\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_dPhi\", \"bkg_dPhi\", \"hadj_dPhi\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_dPhi\", \"bkg_dPhi\", \"hadj_dPhi\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_Xj\", \"bkg_Xj\", \"hadj_Xj\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_Xj\", \"bkg_Xj\", \"hadj_Xj\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_Xj\", \"bkg_Xj\", \"hadj_Xj\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_pTD\", \"bkg_pTD\", \"hadj_pTD\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_pTD\", \"bkg_pTD\", \"hadj_pTD\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_pTD\", \"bkg_pTD\", \"hadj_pTD\", 0.57, 0.03)");
    
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_EmaxOverEcluster.root\", \"sig_Multiplicity\", \"bkg_Multiplicity\", \"hadj_Multiplicity\", 0.50, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_Lambda0.root\", \"sig_Multiplicity\", \"bkg_Multiplicity\", \"hadj_Multiplicity\", 0.54, 0.03)");
    gROOT->ProcessLine(".x background_purity_subtraction.C(\"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"GammaJet_config_clusptmin15.0_clusptmax30.0_JETPTMIN_10.0_DATANAME__13d_0GeVTrack_paired_13e_0GeVTrack_paired_13f_0GeVTrack_paired_PHOTONSELECT_DNN.root\", \"sig_Multiplicity\", \"bkg_Multiplicity\", \"hadj_Multiplicity\", 0.57, 0.03)");
}
